#INITIAL SETTINGS
num_hidden_layer: [ 50, 130 , 100 ]
input_width: 168
output_length: 1 # predict 1 hour
train_ratio: 0.9
epochs: 10
batch_size: 512
features: [ "20"]  # Features to use for training
prediction_feature: "20"  # Feature to use for prediction
optimizer: "adam"
metrics: [ 'mse', 'mae' ]