#INITIAL SETTINGS
kernel_size: 12
nb_filters: 64  # Số lượng filter trong mỗi kernal mask
list_dilation: [1, 2]
input_width: 168
output_length: 1 # predict 1 hour
train_ratio: 0.9
epochs: 10
features: [ "PowerConsumption"]  # Features to use for training
prediction_feature: "PowerConsumption"  # Feature to use for prediction
optimizer: "adam"
metrics: [ 'mse', 'mae' ]